In [11]:
import numpy as np
from math import sqrt
import copy

In [12]:
A = np.array([[6, 5, 0],
              [5, 1, 4],
              [0, 4, 3]])
n = A.shape[0]

###  J(p, q)

In [13]:
Q_ = []
A_ = A.copy()


for i in range(n-1):   
    p = i
    Qi = np.eye(n)
    
    for j in range(i+1, n):
        J = np.eye(n)
        x = A_[:, i]
        q = j
        
        if x[q] != 0:
            if abs(x[p]) >= abs(x[q]):
                t = x[p]/x[q]
                s = 1/sqrt(1 + pow(t, 2))
                c = s*t
            else:
                t = x[q]/x[p]
                c = 1/sqrt(1 + pow(t, 2))
                s = c*t
                
            J[p][p] =  c
            J[q][q] =  c
            J[p][q] =  s
            J[q][p] = -s
            
            Qi = Qi.dot(J)

            A_ = J.dot(A_)
            
            if abs(A_[j][i]) < 0.00001:
                A_[j][i] = 0
    Q_.append(Qi)
               
R = A_

Q = np.eye(n)
for k in range(len(Q_)):
    Q = Q.dot(Q_[k].T)

In [16]:
print('Q', '\n', Q, '\n')
print('R', '\n', R, '\n\n')
print(' A', '\n','Q * R', '\n\n', A, '\n\n', np.round_(Q.dot(R), decimals=8))

Q 
 [[ 0.76822128 -0.33265418 -0.54697099]
 [ 0.6401844   0.39918502  0.65636519]
 [ 0.         -0.854396    0.51962244]] 

R 
 [[ 7.81024968  4.4812908   2.5607376 ]
 [ 0.         -4.68166987 -0.96644793]
 [ 0.          0.          4.18432806]] 


 A 
 Q * R 

 [[6 5 0]
 [5 1 4]
 [0 4 3]] 

 [[ 6.  5. -0.]
 [ 5.  1.  4.]
 [ 0.  4.  3.]]
